apiVersion: hcp.hpe.com/v1
kind: Tenant
metadata:
  name: dtsandbox # Update the tenant name 
spec:
  baseimagetag: 202009090453C
  clustername: hcp.mapr.cluster
  clustertype: external
  corelocation: /var/log/mapr/cores
  grouplist:
  - hpecp-tenant-231-member # Update the tenant id 
  - hpecp-tenant-231-admin  # Update the tenant id
  imageregistry: gcr.io/mapr-252711
  loglocation: /var/log/mapr/
  podinfolocation: /var/log/mapr/podinfo
  security:
    environmenttype: hcp
    externalclientsecret: mapr-client-secrets
    externalconfigmap: mapr-external-cm
    externalhivesiteconfigmap: mapr-hivesite-cm
    externalserversecret: mapr-server-secrets
    externalusersecret: mapr-user-secrets
    usesssd: true
  tenantservices:
    hivemetastore:
      count: 1
      image: hivemeta-2.3:202007091835C
    sparkhs:
      count: 1
      image: spark-hs-2.4.4:202009090453C
    tenantcli:
      count: 1
      image: tenantcli-6.1.0:202009090453C
      